### ISSUE TITLE
Bim and fam files are ordered by index

### ISSUE THREAD

**Issue by krrome** [glimix/pandas-plink#1]
Currently the bim and fam files are being sorted by index (df.sort_index(inplace=True)), which is undesirable, bim and fam files are ordered the same way as the genotype matrix - ordering them shuffles the annotation of genotypes.
This is transparent if e.g. samples in the genotype matrix were ordered alphabetically in the first place, but not in any other case.

Edit: The original order can be restored by sorting the dataframes by column "i". it remains questionable though if sorting bim and fam files by index makes sense in the first place

**Comment by Horta** [comment]
Thanks @krrome for the feedback. @fpcasale is taking care of that!

**Comment by Horta** [comment]
Please, have a lookt at https://pypi.python.org/pypi/pandas-plink/ for the new version contemplating that.
